In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("insurance.csv")

In [8]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92,False,Jaipur,retired,High
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94,True,Indore,retired,High

In [9]:
df.shape

(100, 8)

In [10]:
df.columns

Index(['age', 'weight', 'height', 'income_lpa', 'smoker', 'city', 'occupation',
       'insurance_premium_category'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         100 non-null    int64
 1   weight                      100 non-null    float64
 2   height                      100 non-null    float64
 3   income_lpa                  100 non-null    float64
 4   smoker                      100 non-null    bool
 5   city                        100 non-null    str
 6   occupation                  100 non-null    str
 7   insurance_premium_category  100 non-null    str
dtypes: bool(1), float64(3), int64(1), str(3)
memory usage: 5.7 KB

In [14]:
df.describe(include='all')

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
count,100.000000,100.000000,100.000000,100.000000,100,100,100,100
unique,NaN,NaN,NaN,NaN,2,15,7,3
top,NaN,NaN,NaN,NaN,False,Jaipur,retired,Low
freq,NaN,NaN,NaN,NaN,57,9,26,34
mean,47.180000,83.894000,1.713200,18.400600,NaN,NaN,NaN,NaN
std,16.649312,21.020278,0.110205,16.067465,NaN,NaN,NaN,NaN
min,18.000000,51.100000,1.500000,0.530000,NaN,NaN,NaN,NaN
25%,34.750000,63.650000,1.610000,2.897500,NaN,NaN,NaN,NaN
50%,47.000000,82.300000,1.730000,14.122583,NaN,NaN,NaN,NaN
75%,61.000000,101.300000,1.810000,30.162500,NaN,NaN,NaN,NaN
max,75.000000,119.800000,1.900000,50.000000,NaN,NaN,NaN,NaN

In [15]:
df.isnull().sum()

age                           0
weight                        0
height                        0
income_lpa                    0
smoker                        0
city                          0
occupation                    0
insurance_premium_category    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

age                             int64
weight                        float64
height                        float64
income_lpa                    float64
smoker                           bool
city                              str
occupation                        str
insurance_premium_category        str
dtype: object

In [18]:
df.loc[1:4, ['age', 'weight']]

   age  weight
1   36   101.1
2   39    56.8
3   22   109.4
4   69    62.2

In [24]:
df.iloc[0:, 0:4]

    age  weight  height  income_lpa
0    67   119.8    1.56     2.92000
1    36   101.1    1.83    34.28000
2    39    56.8    1.64    36.64000
3    22   109.4    1.55     3.34000
4    69    62.2    1.60     3.94000
..  ...     ...     ...         ...
95   36    52.8    1.57    19.64000
96   26   113.8    1.54    34.01000
97   52    60.8    1.80    44.86000
98   27   101.1    1.82    28.30000
99   40    70.0    1.59    28.16664

[100 rows x 4 columns]

In [26]:
df[df['age'] > 23]

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low
4,69,62.2,1.60,3.94000,True,Indore,retired,High
5,53,62.9,1.66,50.00000,False,Kota,freelancer,Medium
...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low